/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2016-05-27 16:00:31 UTC)
 * on 2016-06-02 at 21:15:11 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.fusiontables;

/**
 * Available OAuth 2.0 scopes for use with the Fusion Tables API.
 *
 * @since 1.4
 */
public class FusiontablesScopes {

  /** Manage your Fusion Tables. */
  public static final String FUSIONTABLES = "https://www.googleapis.com/auth/fusiontables";

  /** View your Fusion Tables. */
  public static final String FUSIONTABLES_READONLY = "https://www.googleapis.com/auth/fusiontables.readonly";

  /**
   * Returns an unmodifiable set that contains all scopes declared by this class.
   *
   * @since 1.16
   */
  public static java.util.Set<String> all() {
    java.util.Set<String> set = new java.util.HashSet<String>();
    set.add(FUSIONTABLES);
    set.add(FUSIONTABLES_READONLY);
    return java.util.Collections.unmodifiableSet(set);
  }

  private FusiontablesScopes() {
  }
}
